[package]
name = "future-examples"
version = "0.1.0"
edition = "2021"
authors = ["Swaraj Yadav <yadav.swaraj@gmail.com>"]

[dependencies]
chrono = "0.4.38"
tokio = { version = "1.38.0" , features = ["full"] }
